---
title: "Análises - Fitness dos robôs gerados."
author: "Valter Lucena"
date: "9 de novembro de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
```

Importa os dados

```{r, warning=FALSE, message=FALSE}
walls <- read.csv(here("data/run_data_walls_400.csv"))
ramfire <- read.csv(here("data/run_data_ramfire.csv"))
crazy <- read.csv(here("data/run_data_crazy.csv"))
tudo <- read.csv(here("data/run_data_400.csv"))

```


Adiciona coluna com o oponente e junta todas as bases em uma só.

```{r, warning=FALSE, message=FALSE}
walls$opponent <- "walls"
ramfire$opponent <- "ramfire"
crazy$opponent <- "crazy"
tudo$opponent <- "all"

categorizados <- rbind(walls, ramfire, crazy, tudo)
```

Plota valores da média da função de adaptação dos indivíduos de cada geração ao longo das gerações

```{r, warning=FALSE, message=FALSE}
categorizados %>% 
  ggplot(aes(x = round, 
             y = avgFit,
             colour = opponent)) +
  geom_line() +
  labs(title = "Média de adaptação dos indivíduos por geração",
       x = "Geração",
       y = "Média de adaptação")
```

Plota os valores da função de adaptaçãos dos indivíduos mais aptos a cada geração.

```{r, warning=FALSE, message=FALSE}
categorizados %>% 
  ggplot(aes(x = round,
             y = bestFit,
             colour = opponent)) +
  geom_line() +
  labs(title = "Valores da função de adaptação dos melhores indivíduos por geração",
       x = "Geração",
       y = "Valor de adaptação")
  
```

Depois das melhorias

```{r, warning=FALSE, message=FALSE}
walls_novo <- read.csv(here("data/run_data_wall_melhorias.csv"))
ramfire_novo <- read.csv(here("data/run_data_ramfire_melhorias.csv"))
crazy_novo <- read.csv(here("data/run_data_crazy_melhorias.csv"))
tudo_novo <- read.csv(here("data/run_data_melhorias.csv"))

```



```{r, warning=FALSE, message=FALSE}
walls_novo$opponent <- "new_walls"
tudo_novo$opponent <- "new_all"
crazy_novo$opponent <- "new_walls"
ramfire_novo$opponent <- "new_walls"

categorizados_novo <- rbind(walls_novo, tudo_novo, crazy_novo, ramfire_novo)

```

```{r, warning=FALSE, message=FALSE}
categorizados_novo %>% 
  ggplot(aes(x = round, 
             y = avgFit,
             colour = opponent)) +
  geom_line() +
  labs(title = "Média de adaptação dos indivíduos por geração",
       x = "Geração",
       y = "Média de adaptação")
```

```{r, warning=FALSE, message=FALSE}
categorizados_novo %>% 
  ggplot(aes(x = round,
             y = bestFit,
             colour = opponent)) +
  geom_line() +
  labs(title = "Valores da função de adaptação dos melhores indivíduos por geração",
       x = "Geração",
       y = "Valor de adaptação")
  
```
